ENV["SEED_FORCE_RESET"] = "1"

# ------------------------------------------------------------------------------
# Clientes de API (usados quando não se usa SEED_BULK=1)
# ------------------------------------------------------------------------------
module SeedApi
  class IntegrationClient
    def initialize
      @session = ActionDispatch::Integration::Session.new(Rails.application)
      @session.host! "localhost"
    end

    def post_json(path, params_hash)
      @session.post(path, params: params_hash, as: :json)
      { code: @session.response.status, body: safe_parse(@session.response.body) }
    end

    private
      def safe_parse(body)
        return {} if body.blank?

        JSON.parse(body)
      rescue JSON::ParserError => e
        preview = body.to_s.delete("\r")[0, 400]
        raise JSON::ParserError,
              "#{e.message} (a resposta não parece JSON; primeiros bytes: #{preview.inspect})"
      end
  end

  class CurlClient
    def initialize(base_url)
      @base = base_url.to_s.sub(%r{/\z}, "")
      require "open3" unless defined?(Open3)
    end

    def post_json(path, params_hash)
      url  = "#{@base}#{path}"
      json = params_hash.to_json
      out, err, st = Open3.capture3(
        "curl", "-sS", "-X", "POST",
        "-H", "Content-Type: application/json",
        "-d", json,
        "-w", "__HTTP__%{http_code}",
        url
      )
      raise "curl falhou: #{err.presence || st}" unless st.success?

      m = out.match(/\A(.*)__HTTP__(\d+)\z/m)
      raise "saída inesperada do curl" unless m

      body_str = m[1]
      code     = m[2].to_i
      { code: code, body: body_str.present? ? JSON.parse(body_str) : {} }
    end
  end

  def self.client
    return @client if defined?(@client) && @client

    @client = if ENV["SEED_USE_CURL"] == "1"
      CurlClient.new(ENV.fetch("SEED_API_BASE", "http://127.0.0.1:3000"))
    else
      IntegrationClient.new
    end
  end
end

# ------------------------------------------------------------------------------
# Configuration & helpers
# ------------------------------------------------------------------------------
POSTS_TARGET  = 200000
USERS_COUNT   = 100
IP_COUNT      = 50
RATING_P      = 0.75
INSERT_BATCH  = (ENV["SEED_INSERT_BATCH"].presence || 2500).to_i
INSERT_BATCH  = 500 if INSERT_BATCH < 1

USER_LOGINS = (1..USERS_COUNT).map { |i| format("seed_user_%04d", i) }.freeze
IPS         = (1..IP_COUNT).map { |i| "10.201.0.#{i}" }.freeze

def api_client_class_name
  if ENV["SEED_USE_CURL"] == "1"
    "SeedApi::CurlClient"
  else
    "SeedApi::IntegrationClient"
  end
end

def seed_api_client
  SeedApi.client
end

def seed_large_via_bulk
  now = Time.current
  $stderr.puts "[seeds] inserindo usuários..."

  User.insert_all(
    USER_LOGINS.map { |login| { login: login, created_at: now, updated_at: now } }
  )
  user_id_by_login = User.pluck(:login, :id).to_h
  user_ids         = USER_LOGINS.map { |l| user_id_by_login.fetch(l) }

  post_ids = Array.new(POSTS_TARGET)
  $stderr.puts "[seeds] inserindo posts em lotes de #{INSERT_BATCH}..."

  (0...POSTS_TARGET).each_slice(INSERT_BATCH) do |indices|
    rows = indices.map do |i|
      login = USER_LOGINS[i % USERS_COUNT]
      {
        user_id:    user_id_by_login.fetch(login),
        title:      "Seed post ##{i}",
        body:       "Autogenerated body for seed index #{i}.",
        ip:         IPS[i % IP_COUNT],
        created_at: now,
        updated_at: now
      }
    end

    result = Post.insert_all(rows, returning: %w[ id ])
    result.rows.each_with_index do |row, j|
      post_ids[indices[j]] = row[0]
    end

    n = indices.last + 1
    $stderr.puts "[seeds] posts: #{n} / #{POSTS_TARGET}" if (n % 50_000).zero?
  end

  rng   = Random.new(ENV["SEED_RANDOM_SEED"]&.to_i || 42)
  batch = []
  n_ratings = 0

  $stderr.puts "[seeds] gerando e inserindo avaliações (lotes de #{INSERT_BATCH})..."

  POSTS_TARGET.times do |i|
    next if rng.rand >= RATING_P

    post_id   = post_ids[i]
    author_id = user_ids[i % USERS_COUNT]

    rater_id = nil
    8.times do
      r = user_ids[rng.rand(USERS_COUNT)]
      next if r == author_id && USERS_COUNT > 1

      rater_id = r
      break
    end
    rater_id ||= user_ids[rng.rand(USERS_COUNT)]

    batch << {
      post_id:    post_id,
      user_id:    rater_id,
      value:      1 + rng.rand(5),
      created_at: now,
      updated_at: now
    }
    n_ratings += 1

    if batch.size >= INSERT_BATCH
      Rating.insert_all(batch)
      batch.clear
      $stderr.puts "[seeds] avaliações inseridas: ~#{n_ratings}" if (n_ratings % 50_000).zero?
    end
  end

  Rating.insert_all(batch) if batch.any?
  $stderr.puts "[seeds] avaliações concluídas (total ~#{n_ratings})"
end

class SeedLargeViaApiService
  def initialize(client:)
    @client = client
  end

  def call
    user_id_by_login, post_ids = create_posts_via_api
    create_ratings_via_api(user_id_by_login: user_id_by_login, post_ids: post_ids)
  end

  private
    attr_reader :client

    def create_posts_via_api
      user_id_by_login = {}
      post_ids = []

      POSTS_TARGET.times do |i|
        login = USER_LOGINS[i % USERS_COUNT]
        ip    = IPS[i % IP_COUNT]

        res = client.post_json("/posts", {
          title: "Seed post ##{i}",
          body:  "Autogenerated body for seed index #{i}.",
          login: login,
          ip:    ip
        })

        unless res[:code] == 201
          $stderr.puts "[seeds] POST /posts falhou no índice #{i} HTTP #{res[:code]} body: #{res[:body].inspect}"
          abort "POST /posts falhou no índice #{i} (HTTP #{res[:code]})"
        end

        body = res[:body]
        post_ids << body.dig("post", "id")

        user_payload = body["user"]
        if user_payload.is_a?(Hash) && user_payload["login"] && user_payload["id"]
          user_id_by_login[user_payload["login"]] = user_payload["id"]
        end

        if (i + 1) % 10_000 == 0
          $stderr.puts "[seeds] posts: #{i + 1} / #{POSTS_TARGET}"
        end
      end

      if user_id_by_login.size < USERS_COUNT
        abort "[seeds] Esperados #{USERS_COUNT} logins de usuário distintos nas respostas da API; obtidos #{user_id_by_login.size}."
      end

      [ user_id_by_login, post_ids ]
    end

    def create_ratings_via_api(user_id_by_login:, post_ids:)
      user_ids = USER_LOGINS.map { |login| user_id_by_login.fetch(login) }
      rng      = Random.new(ENV["SEED_RANDOM_SEED"]&.to_i || 42)
      rated    = 0

      POSTS_TARGET.times do |i|
        next if rng.rand >= RATING_P

        post_id   = post_ids[i]
        author_id = user_ids[i % USERS_COUNT]

        10.times do |attempt|
          rater_id = user_ids[rng.rand(USERS_COUNT)]
          next if rater_id == author_id && USERS_COUNT > 1

          value   = 1 + rng.rand(5)
          payload = { post_id: post_id, user_id: rater_id, value: value }
          res     = client.post_json("/ratings", payload)
          if res[:code] == 201
            rated += 1
            break
          end
          next if attempt < 9

          $stderr.puts "[seeds] não foi possível avaliar post_id=#{post_id} após tentativas: último HTTP #{res[:code]}"
        end

        if rated.positive? && (rated % 10_000).zero?
          $stderr.puts "[seeds] avaliações criadas: #{rated} (iteração do post #{i + 1})"
        end
      end
    end
end

def seed_large_via_api
  SeedLargeViaApiService.new(client: seed_api_client).call
end

# ------------------------------------------------------------------------------
# Esvaziar tabelas (opção)
# ------------------------------------------------------------------------------
if ENV["SEED_FORCE_RESET"] == "1"
  $stderr.puts "[seeds] esvaziando ratings, posts, users..."
  [ Rating, Post, User ].each(&:delete_all)
  $stderr.puts "[seeds] esvaziamento concluído"
elsif User.exists? || Post.exists? || Rating.exists?
  $stderr.puts "[seeds] Abortado: as tabelas não estão vazias. Defina SEED_FORCE_RESET=1 para apagar e semear de novo, ou use um banco limpo."
  exit 1
end

# ------------------------------------------------------------------------------
# Execução
# ------------------------------------------------------------------------------
if ENV["SEED_BULK"] == "1"
  $stderr.puts "[seeds] modo=bulk insert_all (NÃO passa pelos controllers) lote #{INSERT_BATCH} POSTS_TARGET=#{POSTS_TARGET}"
  seed_large_via_bulk
else
  $stderr.puts "[seeds] modo=API (requisito enunciado) client=#{api_client_class_name} POSTS_TARGET=#{POSTS_TARGET}"
  seed_large_via_api
end

# ------------------------------------------------------------------------------
# Resumo
# ------------------------------------------------------------------------------
puts "Seed concluído."
puts "  Posts:   #{Post.count} (objetivo #{POSTS_TARGET})"
puts "  Usuários: #{User.count} (objetivo #{USERS_COUNT})"
puts "  IPs:     #{Post.distinct.count(:ip)} distintos (esperado #{IP_COUNT})"
puts "  Avaliações: #{Rating.count} (esperado ~#{(POSTS_TARGET * RATING_P).round})"
